### ISSUE TITLE
Can't find hourly forecast

### ISSUE THREAD

**Issue by svenove** [chunkysteveo/OpenEPaperLink-HA-Weatherman#1]
The instructions says to enable hourly forecast, but I can't figure out how...
I'm new to HASS, so it might be just me... 

I've looked at the entities to the Met.no integration, and set to show disabled entities too, but it's still not there...

**Comment by svenove** [comment]
I found this in the release notes, perhaps the entity isn't created on fresh installs (I installes HASS just a few weeks ago):
https://www.home-assistant.io/blog/2023/09/06/release-20239/#weather-forecast-service

What changes needs to be done to support the new "forecast"-method?

**Comment by chunkysteveo** [comment]
Ahhh... good point! I've had mine running for years, before the new weather forcast/setup in HA. I'll look to get it working for the new version of the weather forcast setup the HA works with now.

**Comment by chunkysteveo** [comment]
Is it perhaps a disabled entity, see screenshot - if you go to your entities and search for "forecast" and check the filter for hidden or disabled entities??
![Screenshot_20231014_161634_Home Assistant](https://github.com/chunkysteveo/OpenEPaperLink-HA-Weatherman/assets/14663002/64bead38-e598-4f8b-b20b-d548fe1786e2)

**Comment by svenove** [comment]
No hidden/disabled entities either.

**Comment by chunkysteveo** [comment]
Not sure if this is old, but does this help?

https://community.home-assistant.io/t/met-no-forecast/228366

**Comment by svenove** [comment]
No, it just suggests the same as in your screenshot. 😊

**Comment by chunkysteveo** [comment]
Fixed it @svenove  - check the new [ha-configuration.yaml](https://github.com/chunkysteveo/OpenEPaperLink-HA-Weatherman/blob/main/ha-configuration.yaml) update - it's now using the "get forecast" service in the template to get the hourly forecast data from met.no and populate the Weatherman template with this new data. Tested and working - the hourly option was indeed removed from the met.no integration.

Replace your Weatherman Tag template sensor with this one, and the rest should work fine.
