### ISSUE TITLE
Test 4.2 Variables

### ISSUE THREAD

**Issue by chunkysteveo** [chunkysteveo/OpenEPaperLink-HA-Weatherman#10]
hey @svenove  - i've updated the automation to use variables, so the "severe weather" types and low temp can be stored in an array, and each "cond" checked against this to make it red/black.

It's working on my 2.9" tag perfect. 

I have updated your 4.2" automation with the new variables, and also added wind_speed and precipitation (10 and 10) checks too.

Can you test this new automation yaml and check it works for you, for me? 

Thanks - Steve

**Comment by svenove** [comment]
Great addition to use the variables!
I've fixed a few minor things and made a PR. :)

**Comment by chunkysteveo** [comment]
Awesome, thanks!

I thought I caught all the "rain and wind" variables, but missed those one, d'oh! haha

Thanks for the test and the updates!
