### ISSUE TITLE
Can’t get either 4.2” automation working - Error rendering data template: TypeError: %d format: a real number is required, not str

### ISSUE THREAD

**Issue by nigels0** [chunkysteveo/OpenEPaperLink-HA-Weatherman#14]

**Comment by chunkysteveo** [comment]
You need to change the format of the time string in the HA-Configuration sensor - see the readme about this issue here - https://github.com/chunkysteveo/OpenEPaperLink-HA-Weatherman?tab=readme-ov-file#time-format

**Comment by chunkysteveo** [comment]
I've updated automation-4.2.yaml script, but automation-4.2-kitchen-sink.yaml version should have worked out the box with the current version of ha-configuration.yaml ? Can you elaborate on this if it's still an issue?

**Comment by chunkysteveo** [comment]
OK, as found in another issue - we need to update the automation script for the times, for time_0,time_1,time_2,time_3 to the following (replacing wm_time_0 with 0,1,2,3 etc based on the time attribute you are printing):

`{{ '%0.2d' | format(state_attr('sensor.weatherman_data_tag','wm_time_0') | int) | string | upper }}`

Note the inclusion of the ` | int` in the line of code, which is missing in your automation, and causes an error.
