### ISSUE TITLE
Cannot open resource

### ISSUE THREAD

**Issue by ctrebler** [chunkysteveo/OpenEPaperLink-HA-Weatherman#15]
My automation reports that it cannot find the resource.
![image](https://github.com/chunkysteveo/OpenEPaperLink-HA-Weatherman/assets/101871095/022c8c56-32e3-431d-8a9a-aef30c424197)

If I paste something else into the data on the automation it works perfectly fine ie: 
  background: white
  rotate: 270
  ttl: 300
  payload:
    - type: rectangle
      outline: red
      fill: white
      width: 5
      x_start: 10
      y_start: 10
      x_end: 185
      y_end: 240   
    - type: line
      fill: red
      width: 3
      x_start: 0
      y_start: 237
      x_end: 196
      y_end: 240  
    - type: text
      value: "Hello World!"
      font: "ppb.ttf"
      x: 0
      "y": 0
      size: 40
      color: red
    - type: icon
      value: account-cowboy-hat
      x: 60
      y: 120
      size: 120
      color: red

Any clue on where to start?

**Comment by svenove** [comment]
Have you out the font-file in the correct folder?

**Comment by ctrebler** [comment]
Yes, I can also use the font in the code mention above.

**Comment by chunkysteveo** [comment]
And Gotham font is in the right folder too?

Can we also see the output of your weatherman template sensor?

**Comment by ctrebler** [comment]
I reinstalled the AP firmware and the met.no service and it woks now!
Thanks for the quick support!
![image](https://github.com/chunkysteveo/OpenEPaperLink-HA-Weatherman/assets/101871095/6dc963d6-8b42-4546-ae7f-02494b60b35a)

**Comment by chunkysteveo** [comment]
Haha... a mystery solved, I guess?! 

Glad it's working!
