### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MrGlad8** [chunkysteveo/OpenEPaperLink-HA-Weatherman#16]
I cant execute this. I get error:
Error: Error rendering data template: TypeError: '>' not supported between instances of 'NoneType' and 'int'

Oh, and the Variables wont copy over when I copy the code. I think they need to be added separate in the automation, right?

**Comment by chunkysteveo** [comment]
That sounds like your sensors/variables are not correct as the template sensor is trying to check for a value greater than. Could be linked to you not being able to addnin your variables?

We'd need more info to help further?

Steve

**Comment by MrGlad8** [comment]
Well I just followed the guide, I'm not so into coding :) But I see many of the Weatherman's attributes is "null" - is that a problem?

**Comment by MrGlad8** [comment]
I doesnt seem to get the Weatherman-sensor! And since I use a separate template-sensor I guess I cant copy that code right into templates.yaml right? Do I have to use the trigger for its own automation or can I copy that over to the templates.yaml?

**Comment by MrGlad8** [comment]
Sorry it was my bad, I got the Weatherman-sensor working now :)
But the automation wont work, it gives me error: 
Stopped because an error was encountered at February 29, 2024 at 22:04:10 (runtime: 0.19 seconds)
cannot open resource

And I just tried send another thing to the display and it worked. Any idea where to search for an solution?

**Comment by svenove** [comment]
Did you upload the font file to the correct folder?

**Comment by MrGlad8** [comment]
Ha! I though I was.. but I had put it in the wrong media folder. Now it works. Sorry to bother you :) Thanks for this :)

**Comment by chunkysteveo** [comment]
> Did you upload the font file to the correct folder?

Thanks for the quick response!

Can we close this issue @MrGlad8 , is it working for you now?
