### ISSUE TITLE
fter today's Homeassistant update, the ha-configuration.yaml no longer works if you have set it to 24h.

### ISSUE THREAD

**Issue by peterthepeter** [chunkysteveo/OpenEPaperLink-HA-Weatherman#21]
After today's Homeassistant update, the ha-configuration.yaml no longer works if you have set it to 24h.

As soon as I change the data to:
          wm_time_0: >
            {{ as_timestamp(weather_home_hourly.forecast[0].datetime) | timestamp_custom('%H') }}  

the 
sensor.weatherman_data_tag 

becomes unavailable.

in weather.home
the weather data is available.
No matter which config I use.

This definitely worked before the update.
If I use the configuration.yaml (with 12pm etc.) "original" I get the weatherdata.

**Comment by chunkysteveo** [comment]
Ahh yes, the read.me instructions have not been updated for the new get_forecasts service..... If you're changing to 24H, you need to use something like this:

`{{ as_timestamp(weather_home_hourly['weather.home']['forecast'][0].datetime) | timestamp_custom('%H') }}`

Notice the slightly different format with the extra `['weather.home']['forecast']` ?

Just tested on mine, and it doesn't fail, and shows me "00" for midnight, here. Let me know if that fixes it for you? You'll need to update time_0, time_1, time_2, time_3 with similar updates.

**Comment by peterthepeter** [comment]
Thank you, that works perfectly.

**Comment by chunkysteveo** [comment]
> Thank you, that works perfectly.

Boom!! You're welcome - thanks for spotting it!!
