### ISSUE TITLE
Weather entity 'weather.home' does not support 'hourly' forecast when adding Weatherman

### ISSUE THREAD

**Issue by r2kch** [chunkysteveo/OpenEPaperLink-HA-Weatherman#23]
HomeAssistant:
2024.4.1

Setup: 
Added the content of the config file to the configuration.yaml and get the following issue: 

Error: 
`Trigger Update Coordinator: Error executing script. Error for call_service at pos 1: Weather entity 'weather.home' does not support 'hourly' forecast`

Crosscheck: 
I can run it smoothly from the developer tools:
Request:
`service: weather.get_forecasts
target:
  entity_id: weather.forecast_home
data:
  type: hourly
response_variable: weather_home_hourly`

Answer from developer tools:
`weather.forecast_home:
  forecast:
    - condition: partlycloudy
      datetime: "2024-04-07T13:00:00+00:00"
      wind_bearing: 109.8
      cloud_coverage: 98.4
      temperature: 23.3
      wind_speed: 11.5
      precipitation: 0
      humidity: 44
    - condition: partlycloudy
      datetime: "2024-04-07T14:00:00+00:00"
      wind_bearing: 104.6
      cloud_coverage: 90.6
      temperature: 23.4
      wind_speed: 12.2
      precipitation: 0
      humidity: 44
    - condition: partlycloudy
      datetime: "2024-04-07T15:00:00+00:00"
      wind_bearing: 102
      cloud_coverage: 98.4
      temperature: 23.4
      wind_speed: 13.3
      precipitation: 0
      humidity: 44

more removed`

**Comment by r2kch** [comment]
Somehow weather.home was assigned to open meteo, so I renamed them: 

Wrong:
![wrong](https://github.com/chunkysteveo/OpenEPaperLink-HA-Weatherman/assets/129761755/9e217407-c3e5-4d3a-81dc-006f499d9eb4)

Right: 
![right](https://github.com/chunkysteveo/OpenEPaperLink-HA-Weatherman/assets/129761755/be8a0352-e7ce-49c6-ba4b-5306d1bb4d56)

**Comment by chunkysteveo** [comment]
Good catch - glad you found your fix and resolved! 👍
