### ISSUE TITLE
Error: Non valid icon used: moon-new-moon

### ISSUE THREAD

**Issue by peterthepeter** [chunkysteveo/OpenEPaperLink-HA-Weatherman#25]
Since yesterday I have a new error: moon-new-moon in my Automation.

My moon.phase entity show (see picture).
![Bildschirmfoto 2024-04-08 um 15 14 57](https://github.com/chunkysteveo/OpenEPaperLink-HA-Weatherman/assets/74273835/29e4358d-61fc-4217-8206-1244d3f8c1c1)

my weatherman:
![Bildschirmfoto 2024-04-08 um 15 19 08](https://github.com/chunkysteveo/OpenEPaperLink-HA-Weatherman/assets/74273835/960c7cf5-b4a2-434f-8646-421a003d3d2c)

**Comment by peterthepeter** [comment]
ahh You have already adjusted the config.

**Comment by chunkysteveo** [comment]
Haha yes.. someone else spotted the Moon issue!

Glad it's sorted!
