### ISSUE TITLE
Weatherman stopped working

### ISSUE THREAD

**Issue by nigels0** [chunkysteveo/OpenEPaperLink-HA-Weatherman#26]
Strangely after an update to the latest HA, the weatherman data tag isn't updating - getting an unknown state.

I installed the template again, but that didn't seem to make a difference. Is this just me?

**Comment by svenove** [comment]
Probably same as a lot of the recent issues:
https://github.com/chunkysteveo/OpenEPaperLink-HA-Weatherman/issues?q=is%3Aissue+is%3Aclosed

Replace your configuration from the updated version in the repo. :)

**Comment by nigels0** [comment]
Looks like it! Thanks.

**Comment by chunkysteveo** [comment]
HA has had a lot of changes - a fresh sensor and automation is recommended 👌🏻  Glad you got it sorted!
