### ISSUE TITLE
Show days in own language

### ISSUE THREAD

**Issue by svenove** [chunkysteveo/OpenEPaperLink-HA-Weatherman#3]
As I understand, the `timestamp_custom('%a')` only returns the english version of the weekday and that is a limitation in HASS OS.
It seems there is a "mapping function" that can be used to manually enter the local abbrivations of the weekdays in a list, that will replace the "%a" returned english weekdays.

But, it's a bit too complicated for me to figure out how to implement it in the template...
See the solution here:
https://community.home-assistant.io/t/day-and-month-does-not-follow-locale-setting/406491/4

**Comment by chunkysteveo** [comment]
I've updated the file https://github.com/chunkysteveo/OpenEPaperLink-HA-Weatherman/blob/main/ha-configuration.yaml with a local array map using the numeric day of week (0 = SUNDAY). Replace your code for your "Weatherman" template sensor with this update, and update the arrays:

["Sun","Mon","Tue","Wed","Thu","Fri","Sat"]

With your local days of the week. Sun = Sunday = day "0" = Dimanche, etc, etc
