### ISSUE TITLE
Cannot get this working

### ISSUE THREAD

**Issue by AseKarlsson** [chunkysteveo/OpenEPaperLink-HA-Weatherman#30]
Hi,

New to ePaper but bought a YelloAP and connected a Sollum 2.9” to it fine and it is also exposed to HA with entity open_epaper_link.0000021eeb8a0000.

I have installed the integrations:
Met.no
Moon
Sun

I added the code from ha-configuration.yaml to my teamplates.yaml without modifying anything in the code.
I added the code from automation-2.9.yaml to my automations.yaml and only changed the target to the right open_epaper_link.0000021eeb8a0000.

Also copied the GothamRnd-Bold.ttf to the config/media folder.

I do not get updates to the 2.9” display.

Have I missed something and how to troubleshoot?

Thanks,
Ase

**Comment by chunkysteveo** [comment]
Cam you paste the output of your weatherman sensor?

**Comment by AseKarlsson** [comment]
Thanks for the fast reply, you mean sensor.weatherman_data_tag?
How to see the Output?
Sorry for being novice :(

**Comment by AseKarlsson** [comment]
Is it this:
![image](https://github.com/chunkysteveo/OpenEPaperLink-HA-Weatherman/assets/80900477/aa020161-5c8a-4d23-865c-01cffccb26af)

**Comment by AseKarlsson** [comment]
Get this when I runf Trace on the automation "Error: cannot open resource"

**Comment by AseKarlsson** [comment]
Found it! The media folder was placed wrong!

**Comment by chunkysteveo** [comment]
Glad you found the issue!
