### ISSUE TITLE
Help with time format 12h -> 24h

### ISSUE THREAD

**Issue by AseKarlsson** [chunkysteveo/OpenEPaperLink-HA-Weatherman#31]
Thanks for a great Integration,
I see in the "<> Code" part info for 24 time format.

Sadly I do not understand where in the code I should put this?
Any Example?

Thanks,
Ase

**Comment by AseKarlsson** [comment]
Think I now understand what to change in the code. Testing tomorrow!

**Comment by AseKarlsson** [comment]
I think this has to be changed in 8 places, right?

**Comment by chunkysteveo** [comment]
Glad you found the right place!

**Comment by chunkysteveo** [comment]
> I think this has to be changed in 8 places, right?

The 24 or AM PM is only for the first four timestamps, for the next 4 hour forecasts. The future daily forecasts are day 'stamps', not timestamps - so no 24 or AM/PM formatting needed.
