### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by krissen** [chunkysteveo/OpenEPaperLink-HA-Weatherman#6]
Hi. For some reason, I didn't have a `weather.home` but a (let's call it) `weather.mylocation`. Updated the template and automation accordingly.

The template updates alright (attribute data below), but the automation fails with the following:

```python
2023-11-13 22:20:20.290 ERROR (MainThread) [homeassistant.components.automation.epaper_weatherman] While executing automation automation.epaper_weatherman
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 655, in async_trigger
    await self.action_script.async_run(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1578, in async_run
    return await asyncio.shield(run.async_run())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 420, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 470, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 493, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2035, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2072, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/open_epaper_link/__init__.py", line 44, in drawcustomservice
    imgbuff = await hass.async_add_executor_job(customimage,entity_id, service, hass)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/open_epaper_link/imagegen.py", line 181, in customimage
    data = json.load(f)
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
                 ^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 2286967: invalid continuation byte
```

This is the attribute data for the weather man template sensor:
```yaml
moon_phase: moon-new
wm_cond_now: cloudy
wm_cond_0: night-partly-cloudy
wm_temp_0: -1
wm_time_0: 10 PM
wm_cond_1: cloudy
wm_temp_1: -1
wm_time_1: 11 PM
wm_cond_2: cloudy
wm_temp_2: -1
wm_time_2: 12 AM
wm_cond_3: cloudy
wm_temp_3: -1
wm_time_3: 1 AM
wm_cond_4: cloudy
wm_temp_4: -1
wm_temp_4_low: -2
wm_time_4: Mon
wm_cond_5: cloudy
wm_temp_5: 1
wm_temp_5_low: -1
wm_time_5: Tue
wm_cond_6: cloudy
wm_temp_6: 0
wm_temp_6_low: -2
wm_time_6: Wed
wm_cond_7: cloudy
wm_temp_7: -2
wm_temp_7_low: -4
wm_time_7: Thu
friendly_name: Weatherman Data Tag
```

Apart from the temperature unit, I can't really see what else the automation could throw a fit about. Have checked pretty much all of the template-code in the automation, and all seems to check it.

```yaml
{{ state_attr('weather.mylocation','temperature_unit') }}
```
```yaml
Resultattyp: string
°C
```

Font is in place. Latest openepaper HA integration and HA 2023.11.2.

Any ideas?

**Comment by krissen** [comment]
If I remove all of the icons, the automation works. So probably one of them. Investigating further.

**Comment by krissen** [comment]
Well, there weren't that many different conditions. First one I tried adding back, `wm_cond_6` was "cloudy". The result of the icon value template is `weather-cloudy`, which checks out. 

Only text, no problem. If I add this one back, errors out as reported above. If I have only this icon for the drawcustom task in the automation, it errors out as reported above.

**Comment by chunkysteveo** [comment]
Hmmm.... the errors are coming from the HA Epaper plugin, and not drawing the icons... very odd indeed. I can test your Weatherman sensor data to see if I get similar results. But here in the UK its always Cloudy...!!! So that icon is always fine(!!)

Can you get the test HA Epaper plugin example draw custom icon working - the one with the 'cowboy hat' from his repo? Just to check the repo is working with your tags all ok? If it fails at that - there may be a setup issue.

**Comment by krissen** [comment]
Downgraded the openepaper HA integration from latest 0.3.5.2 to 0.3.5 -- icons are drawn. I'll close this and report there instead. Thanks for your prompt reply anyway!

**Comment by chunkysteveo** [comment]
Ohhh that's interesting!! I'm still on 0.3.2 so quite behind... but maybe I will keep an eye on this issue. Thanks for spotting it and closing down my issue. Hope it gets sorted for you soon 🙏🏻

**Comment by zarqeon** [comment]
Just an idea:
I too have an automation that uses a weather forecast service to draw weather icons.
I had problems with the 'partlycloudy' and 'clear-night', because i just plugged what comes as current condition into the value of the icon.
but here is no mdi:weather-partlycloudy, it's called mdi:weather-partly-cloudy.
also there is no mid:weather-clear-night, it's called mdi:weather-night
These I have to map manually (i use if statements) like this:
`    - type: icon
      value: >-
        {%- if states('sensor.openweathermap_condition') == 'partlycloudy' -%}
        weather-partly-cloudy {%- elif states('sensor.openweathermap_condition')
        == 'clear-night' -%} weather-night {%- else -%} weather-{{
        states('sensor.openweathermap_condition') }} {%- endif -%}`

I am not sure if this is the case for you as well, but it might be worth to take a look. Though if it works with an older version then it suggests that this won't help.

**Comment by krissen** [comment]
@zarqeon Thanks for the suggestion. Yes, what you describe is necessary, and already handled by the template sensor. The proper icons were used; the issue also happened with the openepaper integration's cowboy example etc.

**Comment by chunkysteveo** [comment]
> Just an idea:
> 
> I too have an automation that uses a weather forecast service to draw weather icons. I had problems with the 'partlycloudy' and 'clear-night', because i just plugged what comes as current condition into the value of the icon. but here is no mdi:weather-partlycloudy, it's called mdi:weather-partly-cloudy. also there is no mid:weather-clear-night, it's called mdi:weather-night These I have to map manually (i use if statements) like this:
> 
> > ```
> > - type: icon
> >   value: >-
> >     {%- if states('sensor.openweathermap_condition') == 'partlycloudy' -%}
> >     weather-partly-cloudy {%- elif states('sensor.openweathermap_condition')
> >     == 'clear-night' -%} weather-night {%- else -%} weather-{{
> >     states('sensor.openweathermap_condition') }} {%- endif -%}
> > ```
> 
> I am not sure if this is the case for you as well, but it might be worth to take a look. Though if it works with an older version then it suggests that this won't help.

Thanks - yeah - I've already handled the day/night and the partlycloudy icons. The met.no integration has just been updated too to check for sun.up and sun.down so the Sunny is auto changed to night... but that also needs an icon mapping... another issue with HA, which I had a PR completed to update the documentation as it was misleading. 👍🏻
